replicas: 3
  selector:
    matchLabels:
      app: myapps
    template:
    metadata:
      labels:
        app: myapps
    spec:
      containers:
      - name: docker
        image: dotnet-web:latest
        ports:
        - containerPort: 80
